services:
  epigraph:
    image: ghcr.io/gloaysa/epigraph:latest
    environment:
      NODE_ENV: production
      PORT: "3003"
      BOOKS_FOLDER: /data/books
    ports:
      - "3003:3003"
    volumes:
      - /mnt/public/books:/data/books:ro
    restart: unless-stopped
